<?php require 'header.php' ?>
<?php require 'nav.php' ?>


<!-- DNA Test HEROE SECTION -->
<section class="bg_main" id="dna_serve"></section>
<!-- END OF DNA TestHEROE SECTION -->

<!-- ==================== DNA-TEST SECTION ======================== -->
<section class="bg_main" id="dna_tst">
    <div class="fg_center dna_tst grid_main">
        <div class="text_dn grid1" id="paternity">
            
            <section class="all_sec" id="forensic-dna-service">
                <h3 class="txt_1">Forensic DNA Services</h3>
                <p class="txt_bdy tag_body2">
                Forensic science is basically the application of science to criminal 
                investigations. Evidence from the crime scene are collected, preserved and
                 analyzed during the investigation process. Forensic DNA uses both complete 
                 and partial DNA profile which is generated by using the distinct aspect of our DNA that is unique to us. A DNA profile is a complete description of a person’s 
                appearance while a partial profile describes only one of the traits. <br>
                DNA profiling for forensic science compares criminal suspects’ profiles to DNA 
                evidence in other to ascertain their involvement in the crime. Items such as masks, 
                hats, clothing’s, underwear’s, dirty laundry, fingernail scrapings, cups, 
                cigarettes, condoms etc., are used to identify the perpetrator of the crime.
                </p>

                <div class="btn_2" >
                    <div  class="btn_auto">
                        <a href="contact" class="hd_btn">Book Now</a>
                    </div>
                </div>
            </section>

        </div>

        <div class="img_dn list grid1" id="nav">
            <ul>
                <li class="active_nav">
                    <a href="#forensic-dna-service">Forensic DNA Services</a>
                </li>
            </ul>
        </div>

    </div>

    <!-- ==================== CONNECT SECTION ======================== -->
    <section class="bg_main talk_sect" >
        <div class="fg_center ">
            <div class="srv_bg">
                <div class="connect__1" data-aos="fade-up" data-aos-duration="3400">
                    <div class="title">
                        <h2 class="sub__title con__title" style="margin-bottom:10px !important;">Still Need Help?</h2>
                    </div>
                    <p id="srv_par">No worries, contact us directly for a confidential consultation. It’s free</p>
                </div>
    
                <div class="connect_btn" data-aos="fade-up" data-aos-duration="3400">
                    <a href="contact" class="srv_btn">
                        <div class="img_dn">
                            <img src="img/Call.png" alt="Test">
                        </div>
                        Talk to Us
                    </a>
                </div>
            </div>
        </div>
    
    </section>
    
    <!-- ==================== END CONNECT SECTION ======================== -->

</section>
<!-- ==================== END OF DNA-TEST SECTION ======================== -->


<!-- modal section -->
<?php require 'modal-section.php' ?>
<!--  end modal -->

<?php require 'footer.php' ?>
